CREATE DATABASE IF NOT EXISTS yokegame;
USE yokegame;

DROP TABLE IF EXISTS yoke_score;

CREATE TABLE yoke_score (
  id INT(10) AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(10) NOT NULL,
  score INT(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
